version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current  # Lance une VM Ubuntu 22.04
    steps:
      - checkout  # Récupère le code source
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER
            newgrp docker
      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .

  test:
    machine:
      image: ubuntu-2204:current  # Utilise aussi une VM Ubuntu
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER
            newgrp docker
      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .
      - run:
          name: Run Docker Container
          command: docker run -d -p 3000:3000 --name test-container my-node-app
      - run:
          name: Test API Response
          command: |
            sleep 5
            curl --fail http://localhost:3000 || exit 1

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER
            newgrp docker
      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag and Push Image
          command: |
            docker tag my-node-app $DOCKERHUB_USERNAME/my-node-app:latest
            docker push $DOCKERHUB_USERNAME/my-node-app:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
