version: 2.1

executors:
  linux-executor:
    docker:
      - image: circleci/python:3.8  # Utilisation d'une image Docker de base avec Python (on peut remplacer par d'autres si besoin)
    working_directory: ~/repo

jobs:
  build:
    executor: linux-executor
    steps:
      - checkout  # Récupère le code du dépôt
      - run:
          name: Installer Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Construire l'image Docker
          command: |
            docker build -t node-js-app .
      - run:
          name: Lancer le conteneur Docker
          command: |
            docker run -d -p 8080:8080 --name node-js-container node-js-app
      - run:
          name: Tester si l'application répond sur le port 8080
          command: |
            curl -f http://localhost:8080 || exit 1
      - run:
          name: Pousser l'image Docker sur Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag node-js-app $DOCKER_USERNAME/node-js-app:latest
            docker push $DOCKER_USERNAME/node-js-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
